name: Bug report
title: "[bug] <title>"
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Make sure to keep the name of your bug report short and descriptive.
        In-depth details should not go in the title.
        Please make sure to fill every field correctly.

  - type: checkboxes
    id: bug-prerequisites
    attributes:
      label: Prerequisites
      description: Please verify and check the options below.
      options:
        - label: This is not a feature request.
          required: true
        - label: I checked recent issues and verified that this is not a duplicate.
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and coherent description of the bug.
    validations:
      required: true

  - type: input
    id: bug-browser
    attributes:
      label: What browser are you seeing the problem on?
    validations:
      required: true

  - type: textarea
    id: bug-expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and coherent description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: bug-logs
    attributes:
      label: Relevant log output
      description: Did this error throw an error in the console? If so, please copy and paste any relevant log here. (optional)
      render: shell
    validations:
      required: false

  - type: textarea
    id: bug-reproducing
    attributes:
      label: Steps to reproduce the behavior. (optional, but highly appreciated)
      placeholder: |
        1. Go to "..."
        2. Click on "..."
        3. See error
    validations:
      required: false

  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots (optional)
      description: If necessary, add screenshots to help ilustrate your problem.
    validations:
      required: false
